# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Eghan Thompson
tagline: Front End Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am seeking a position that involves ongoing learning and collaboration in an enviornment that embraces change while fostering best practices and practical decision making. I am accustomed to fast paced workplaces that deliver on deadlines while keeping a low stress, focused culture as a priority. I enjoy lateral thinking and problem solving. I thrive on learning, challenge, and working as part of a team.  Practice, patience, and perciverance, are common corner stones I look to.'

#sidebar links
email: eghant@gmail.com
phone: 707 859 ****
website: artofactory.com #do not add http://
linkedin: eghan-thompson-755a6410a
github: eghan
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
